version: '2'
services:
  service:
    build: ./service
    restart: unless-stopped
    environment:
      - SERVICE_ADDRESS=http://192.168.0.24/
      - SERVICE_MONGODB_HOST=mongodb
      - SERVICE_MONGODB_PORT=27017
      - SERVICE_MONGODB_NAME=ducks_content
    ports:
      - 5050:5000
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./service:/usr/src/app

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/mongo/db:/data/db
